### ISSUE TITLE
bool PushData() ? but dont return anything ? 

### ISSUE THREAD

**Issue by BetaIRL** [bdesvc/rat-base#1]
How this should work ? Kinda stuck atm can you help ?

**Comment by bdesvc** [comment]
Isn't not meant to at the current time, I would return false if it fails to get credentials, etc.

**Comment by BetaIRL** [comment]
Is it possible that I can add you on discord. The Client sends a request with the encrypted data but my database is not working correct I think cause its not adding the data._.

**Comment by BetaIRL** [comment]
if($stmt->execute()) return false for me can you help me ?
